services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sensordb
      POSTGRES_USER: sensoruser
      POSTGRES_PASSWORD: sensorpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sensoruser -d sensordb"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_NAME: sensordb
      DATABASE_USER: sensoruser
      DATABASE_PASSWORD: sensorpass
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      SECRET_KEY: "django-insecure-dev-key-change-in-production"
      DEBUG: "True"
    depends_on:
      db:
        condition: service_healthy

  app:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true
    depends_on:
      - web
    stdin_open: true
    tty: true

volumes:
  postgres_data: